import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import type { Hex } from "viem";
import {
  EMPTY_MANIFEST_ROOT,
  inclusionProof,
  merkleRoot,
  nonInclusionProof,
  verifyInclusion,
  verifyNonInclusion,
  type InclusionProof,
  type NonInclusionKind,
  type NonInclusionProof,
} from "../src/merkle.js";

/**
 * TS half of the TS<->Solidity merkle byte-parity claim (D-CR-02). The Solidity
 * half is contracts/test/MerkleParity.t.sol; both read the SAME committed
 * vectors from test/fixtures/merkle.json (generated by `npm run fixture`), so
 * drift on either side of the dual implementation fails a test. Without this
 * file the fixture only ever pinned Solidity: src/merkle.ts could change its
 * node-domain prefix or internal-node byte layout with both suites green,
 * because every other TS merkle assertion is self-referential.
 *
 * Assertions are deliberately two-directional per vector: the SDK must ACCEPT
 * the committed proof (what Solidity checks) and must REPRODUCE it byte-for-byte
 * (what pins the sibling layout the fixture ships to Solidity).
 */

const FIXTURE = JSON.parse(
  readFileSync(join(dirname(fileURLToPath(import.meta.url)), "fixtures", "merkle.json"), "utf8"),
) as Record<string, unknown>;

/** Flat-key reader; the fixture is flat so Foundry's vm.parseJson* can address it. */
function fx<T>(key: string): T {
  if (!(key in FIXTURE)) throw new Error(`merkle.json is missing key ${key}`);
  return FIXTURE[key] as T;
}

function fxInclusion(prefix: string): InclusionProof {
  return {
    leaf: fx<Hex>(`${prefix}_leaf`),
    index: fx<number>(`${prefix}_index`),
    leafCount: fx<number>(`${prefix}_leafCount`),
    siblings: fx<Hex[]>(`${prefix}_siblings`),
  };
}

/** Enum parity with Solidity NonInclusionKind (BelowFirst/AboveLast/Bracket). */
const KIND_BY_UINT: readonly NonInclusionKind[] = ["belowFirst", "aboveLast", "bracket"];

function fxNonInclusion(prefix: string): { targetId: Hex; proof: NonInclusionProof } {
  const kind = KIND_BY_UINT[fx<number>(`${prefix}_kind`)];
  if (kind === undefined) throw new Error(`${prefix}_kind is not a known enum tag`);
  return {
    targetId: fx<Hex>(`${prefix}_targetId`),
    proof: { kind, a: fxInclusion(`${prefix}_a`), b: fxInclusion(`${prefix}_b`) },
  };
}

const CASE8_IDS = fx<Hex[]>("case8_ids");
const CASE8_ROOT = fx<Hex>("case8_root");

describe("merkle fixture parity (TS half of MerkleParity.t.sol)", () => {
  it("reproduces every committed root — this is what pins LEAF_PREFIX/NODE_PREFIX", () => {
    for (const n of [0, 1, 2, 3, 5, 8]) {
      const ids = fx<Hex[]>(`case${n}_ids`);
      expect(ids).toHaveLength(n);
      expect(merkleRoot(ids)).toBe(fx<Hex>(`case${n}_root`));
    }
    expect(fx<Hex>("case0_root")).toBe(EMPTY_MANIFEST_ROOT);
  });

  it("accepts and reproduces every committed inclusion proof", () => {
    for (let i = 0; i < 8; i++) {
      const committed = fxInclusion(`case8_inc${i}`);
      expect(committed.index).toBe(i);
      expect(committed.leafCount).toBe(8);
      // Solidity's direction: the committed proof must verify.
      expect(verifyInclusion(committed, CASE8_ROOT)).toEqual({ ok: true });
      // The fixture's direction: the SDK must emit these exact sibling bytes.
      expect(inclusionProof(CASE8_IDS, i)).toEqual(committed);
    }
  });

  it("accepts and reproduces every committed non-inclusion proof", () => {
    for (const prefix of ["case8_niBelow", "case8_niAbove", "case8_niBracket"]) {
      const { targetId, proof } = fxNonInclusion(prefix);
      expect(verifyNonInclusion(targetId, proof, CASE8_ROOT)).toEqual({ ok: true });
      expect(nonInclusionProof(CASE8_IDS, targetId)).toEqual(proof);
    }
    // Enum order is load-bearing across the ABI boundary; pin the tags too.
    expect(fxNonInclusion("case8_niBelow").proof.kind).toBe("belowFirst");
    expect(fxNonInclusion("case8_niAbove").proof.kind).toBe("aboveLast");
    expect(fxNonInclusion("case8_niBracket").proof.kind).toBe("bracket");
  });

  it("negative vector: the member id never proves non-inclusion (mirrors test_negativeVector)", () => {
    const memberId = fx<Hex>("case8_negMemberId");
    expect(CASE8_IDS.map((id) => id.toLowerCase())).toContain(memberId.toLowerCase());

    // inc3/inc4 puts the member AT the upper anchor; inc4/inc5 puts it AT the
    // lower anchor; inc3/inc5 skips it entirely. Strict inequalities and the
    // adjacency gate must reject all three.
    const attempts: NonInclusionProof[] = [
      { kind: "bracket", a: fxInclusion("case8_inc3"), b: fxInclusion("case8_inc4") },
      { kind: "bracket", a: fxInclusion("case8_inc4"), b: fxInclusion("case8_inc5") },
      { kind: "bracket", a: fxInclusion("case8_inc3"), b: fxInclusion("case8_inc5") },
    ];
    for (const attempt of attempts) {
      expect(verifyNonInclusion(memberId, attempt, CASE8_ROOT).ok).toBe(false);
    }
  });

  it("uppercase-hex input reproduces the committed root (Pitfall 7 parity)", () => {
    expect(merkleRoot(fx<Hex[]>("caseUpper_inputIds"))).toBe(fx<Hex>("caseUpper_root"));
  });
});
