// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

import {Test} from "forge-std/Test.sol";
import {ECDSA} from "@openzeppelin/contracts/utils/cryptography/ECDSA.sol";
import {ClearingHub} from "../src/ClearingHub.sol";
import {MockUSDC} from "./utils/RoundBuilder.sol";

/// @dev Locks EIP-712 encoding parity with the TypeScript SDK: reads the same
///      JSON vector generated by `npm run fixture` (test/genFixture.ts) and
///      asserts the on-chain digest — and signature recovery — match viem's.
contract DigestParityTest is Test {
    function test_digestMatchesSdkFixture() public {
        string memory json = vm.readFile("../test/fixtures/digest.json");

        address hubAddr = vm.parseJsonAddress(json, ".hub");
        uint256 chainId = vm.parseJsonUint(json, ".chainId");
        uint64 nonce_ = uint64(vm.parseJsonUint(json, ".roundNonce"));
        address[] memory participants = vm.parseJsonAddressArray(json, ".participants");
        int256[] memory deltas = vm.parseJsonIntArray(json, ".deltas");
        bytes32 manifestHash = vm.parseJsonBytes32(json, ".manifestHash");
        bytes32 expectedDigest = vm.parseJsonBytes32(json, ".digest");
        address signer0 = vm.parseJsonAddress(json, ".signer0");
        bytes memory consent0 = vm.parseJsonBytes(json, ".consent0");

        // Recreate the fixture's exact domain: chain 5042002, hub at the
        // fixture address (constructor runs elsewhere under deployCodeTo, so
        // OZ EIP712 falls back to computing the separator with live values).
        vm.chainId(chainId);
        MockUSDC usdc = new MockUSDC();
        deployCodeTo("ClearingHub.sol:ClearingHub", abi.encode(address(usdc)), hubAddr);
        ClearingHub hub = ClearingHub(hubAddr);

        bytes32 onchain = hub.hashRound(nonce_, participants, deltas, manifestHash);
        assertEq(onchain, expectedDigest, "TS and Solidity round digests diverge");

        // viem signature must recover on-chain: locks the whole signing path.
        assertEq(ECDSA.recover(onchain, consent0), signer0, "consent signature recovery diverges");
    }
}
