// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

import {Test} from "forge-std/Test.sol";
import {ManifestMerkle} from "../src/lib/ManifestMerkle.sol";

/// @dev Locks merkle construction parity with the TypeScript SDK: reads the
///      same JSON vectors generated by `npm run fixture` (test/genFixture.ts)
///      and asserts ManifestMerkle reproduces viem's roots and accepts/rejects
///      the same inclusion and non-inclusion proofs (MERK-02, D-16). Pure
///      library parity — no hub deployment needed.
contract MerkleParityTest is Test {
    string internal json;

    function setUp() public {
        json = vm.readFile("../test/fixtures/merkle.json");
    }

    /// @dev Reconstructs an InclusionProof from the fixture's flat keys.
    function _inclusionAt(string memory prefix)
        internal
        view
        returns (ManifestMerkle.InclusionProof memory p)
    {
        p.leaf = vm.parseJsonBytes32(json, string.concat(prefix, "_leaf"));
        p.index = vm.parseJsonUint(json, string.concat(prefix, "_index"));
        p.leafCount = vm.parseJsonUint(json, string.concat(prefix, "_leafCount"));
        p.siblings = vm.parseJsonBytes32Array(json, string.concat(prefix, "_siblings"));
    }

    /// @dev Reconstructs a NonInclusionProof (kind uint 0/1/2 -> enum) plus its
    ///      target id from the fixture's flat keys.
    function _nonInclusionAt(string memory prefix)
        internal
        view
        returns (bytes32 targetId, ManifestMerkle.NonInclusionProof memory p)
    {
        targetId = vm.parseJsonBytes32(json, string.concat(prefix, "_targetId"));
        p.kind = ManifestMerkle.NonInclusionKind(
            vm.parseJsonUint(json, string.concat(prefix, "_kind"))
        );
        p.a = _inclusionAt(string.concat(prefix, "_a"));
        p.b = _inclusionAt(string.concat(prefix, "_b"));
    }

    // ------- root parity

    function test_rootParity() public view {
        uint256[6] memory counts = [uint256(0), 1, 2, 3, 5, 8];
        for (uint256 i; i < counts.length; ++i) {
            string memory prefix = string.concat(".case", vm.toString(counts[i]));
            bytes32[] memory ids = vm.parseJsonBytes32Array(json, string.concat(prefix, "_ids"));
            bytes32 expected = vm.parseJsonBytes32(json, string.concat(prefix, "_root"));
            assertEq(ids.length, counts[i], "fixture leaf count mismatch");
            assertEq(ManifestMerkle.rootOf(ids), expected, "TS and Solidity merkle roots diverge");
        }
        bytes32[] memory empty = vm.parseJsonBytes32Array(json, ".case0_ids");
        assertEq(
            ManifestMerkle.rootOf(empty),
            ManifestMerkle.EMPTY_ROOT,
            "empty manifest must commit to the v1 sentinel"
        );
    }

    // ------- inclusion parity

    function test_inclusionParity() public view {
        bytes32 root = vm.parseJsonBytes32(json, ".case8_root");
        for (uint256 i; i < 8; ++i) {
            ManifestMerkle.InclusionProof memory p =
                _inclusionAt(string.concat(".case8_inc", vm.toString(i)));
            assertEq(p.index, i, "fixture proof index mismatch");
            assertTrue(
                ManifestMerkle.verifyInclusion(p, root),
                "TS-generated inclusion proof rejected by Solidity"
            );
        }
    }

    // ------- non-inclusion parity

    function test_nonInclusionParity() public view {
        bytes32 root = vm.parseJsonBytes32(json, ".case8_root");
        string[3] memory prefixes = [".case8_niBelow", ".case8_niAbove", ".case8_niBracket"];
        for (uint256 i; i < prefixes.length; ++i) {
            (bytes32 targetId, ManifestMerkle.NonInclusionProof memory p) =
                _nonInclusionAt(prefixes[i]);
            assertTrue(
                ManifestMerkle.verifyNonInclusion(targetId, p, root),
                "TS-generated non-inclusion proof rejected by Solidity"
            );
        }
    }

    // ------- negative vector: a member id must never prove non-inclusion

    function test_negativeVector() public view {
        bytes32 root = vm.parseJsonBytes32(json, ".case8_root");
        bytes32 memberId = vm.parseJsonBytes32(json, ".case8_negMemberId");

        // Bracket attempt with the member's true neighbors on either side:
        // inc3/inc4 puts the member AT the upper anchor (id < b.leaf fails);
        // inc4/inc5 puts it AT the lower anchor (a.leaf < id fails). Strict
        // inequalities make both structurally-valid brackets reject the member.
        ManifestMerkle.NonInclusionProof memory below;
        below.kind = ManifestMerkle.NonInclusionKind.Bracket;
        below.a = _inclusionAt(".case8_inc3");
        below.b = _inclusionAt(".case8_inc4");
        assertFalse(
            ManifestMerkle.verifyNonInclusion(memberId, below, root),
            "member id proved non-inclusion via bracket at its own upper anchor"
        );

        ManifestMerkle.NonInclusionProof memory above;
        above.kind = ManifestMerkle.NonInclusionKind.Bracket;
        above.a = _inclusionAt(".case8_inc4");
        above.b = _inclusionAt(".case8_inc5");
        assertFalse(
            ManifestMerkle.verifyNonInclusion(memberId, above, root),
            "member id proved non-inclusion via bracket at its own lower anchor"
        );

        // Skipping the member entirely (inc3/inc5) breaks bracket adjacency.
        ManifestMerkle.NonInclusionProof memory skip;
        skip.kind = ManifestMerkle.NonInclusionKind.Bracket;
        skip.a = _inclusionAt(".case8_inc3");
        skip.b = _inclusionAt(".case8_inc5");
        assertFalse(
            ManifestMerkle.verifyNonInclusion(memberId, skip, root),
            "member id proved non-inclusion via non-adjacent bracket"
        );
    }

    // ------- uppercase normalization parity (Pitfall 7)

    function test_uppercaseNormalizationParity() public view {
        // caseUpper_inputIds carries one id rendered in UPPERCASE hex; the SDK
        // lowercased before hashing while Solidity parses bytes32 numerically
        // (case-insensitive). Equal roots prove the SDK's lowercase-hex sort
        // order equals Solidity's numeric bytes32 order.
        bytes32[] memory ids = vm.parseJsonBytes32Array(json, ".caseUpper_inputIds");
        bytes32 expected = vm.parseJsonBytes32(json, ".caseUpper_root");
        assertEq(
            ManifestMerkle.rootOf(ids),
            expected,
            "uppercase-normalized TS root diverges from Solidity bytes32 root"
        );
    }
}
